services:
  app:
    image: php:8.2-fpm
    expose:
      - "9000"
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: hms-hms-jeh7rx
      DB_PORT: 5432
      DB_DATABASE: hms_db
      DB_USERNAME: hms_env_prod
      DB_PASSWORD: KT@Manohar#2025
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wait-for-app.sh:/wait-for-app.sh
    depends_on:
      - app
    command: ["sh", "-c", "until wget -q --spider http://app:8000; do echo 'Waiting for Laravel...'; sleep 2; done && nginx -g 'daemon off;'"]

volumes:
  pgdata: {}
