version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel_net
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: hms_db
      DB_USERNAME: hms_db_user
      DB_PASSWORD: fzz9mxzvnko5egpx
      APP_URL: https://stayhub360.com
      SESSION_DOMAIN: stayhub360.com

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel
    networks:
      - laravel_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stayhub360.rule=Host(`stayhub360.com`)"
      - "traefik.http.routers.stayhub360.entrypoints=websecure"
      - "traefik.http.routers.stayhub360.tls.certresolver=letsencrypt"
      - "traefik.http.services.stayhub360.loadbalancer.server.port=80"

  db:
    image: postgres:17
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: hms_db
      POSTGRES_USER: hms_db_user
      POSTGRES_PASSWORD: fzz9mxzvnko5egpx
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_net

volumes:
  pgdata:

networks:
  laravel_net:
    driver: bridge